# plugins in this file are read every time

[[plugins]]
repo = 'Shougo/dein.vim'

# easy comment out
[[plugins]]
repo = 'tomtom/tcomment_vim'

# change "" , '' , () , and more
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']


[[plugins]]
repo = 'Townk/vim-autoclose'

# [[plugins]]
# repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
	let g:airline_powerline_fonts = 1
	let g:airline#extensions#tabline#enabled = 1
	let g:airline_section_z = airline#section#create(['windowswap', '%3p%% ', 'linenr', ':%3v'])
	let g:airline#extensions#hunks#enabled = 0

	" unicode symbols
	let g:airline_left_sep = 'Â»'
	let g:airline_left_sep = 'â–¶'
	let g:airline_right_sep = 'Â«'
	let g:airline_right_sep = 'â—€'
	let g:airline_symbols.crypt = 'ğŸ”’'
	let g:airline_symbols.linenr = 'ã‘'
	let g:airline_symbols.linenr = 'âŠ'
	let g:airline_symbols.linenr = 'â¤'
	let g:airline_symbols.linenr = 'Â¶'
	let g:airline_symbols.maxlinenr = ''
	let g:airline_symbols.maxlinenr = 'ã‘'
	let g:airline_symbols.branch = 'â‡'
	let g:airline_symbols.paste = 'Ï'
	let g:airline_symbols.paste = 'Ã'
	let g:airline_symbols.paste = 'âˆ¥'
	let g:airline_symbols.spell = 'ê¨'
	let g:airline_symbols.notexists = 'âˆ„'
	let g:airline_symbols.whitespace = 'Î'

	" powerline symbols
	let g:airline_left_sep = 'î‚°'
	let g:airline_left_alt_sep = 'î‚±'
	let g:airline_right_sep = 'î‚²'
	let g:airline_right_alt_sep = 'î‚³'
	let g:airline_symbols.branch = 'î‚ '
	let g:airline_symbols.readonly = 'î‚¢'
	let g:airline_symbols.linenr = 'ã‘'
	let g:airline_symbols.maxlinenr = 'î‚¡'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']
hook_add = '''
	let g:airline_theme = 'jellybeans'
'''

# status line in tmux generator
# [[plugins]]
# repo = 'edkolev/tmuxline.vim'
# hook_add = '''
# let g:tmuxline_preset = {
#       \'a'    : '#S',
#       \'c'    : ['#(whoami)'],
#       \'win'  : ['#I', '#W'],
#       \'cwin' : ['#I', '#W', '#F'],
#       \'x'    : ['#{battery_percentage} #{battery_icon}', '#{cpu_percentage} #{cpu_icon}'],
#       \'y'    : ['%a', '%R', '#(ansiweather -l tokyo -w false -h false -p false -a false | cut -d " " -f7,8,9)'],
#       \'z'    : '#H',
#       \'options' : {'status-justify':'left'}}
# let g:tmuxline_theme = 'papercolor'
# '''

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# for Git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
	let g:ale_sign_column_always = 1
	let g:ale_sign_error = 'e>'
	let g:ale_linters = {'go': ['gofmt']}
'''

# ---------- color schemes ----------------

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  set background=dark
  autocmd ColorScheme * highlight Normal ctermbg=none guibg=none
  autocmd ColorScheme * highlight LineNr ctermbg=none guibg=none
  " colorscheme è¨­å®šã¯ source å¾Œã«è¡Œã†å¿…è¦ãŒã‚ã‚‹ã®ã§ VimEnter ã§è¡Œã†ã€‚
  " ä½†ã— Colorscheme ã‚¤ãƒ™ãƒ³ãƒˆã®ç™ºç”ŸãŒæŠ‘åˆ¶ã•ã‚Œãªã„ã‚ˆã† nented ã‚’ä»˜ã‘ã‚‹ã€‚
  au VimEnter * nested colorscheme gruvbox
'''

# ---------- other languages --------------

# for Elixir
[[plugins]]
repo = 'elixir-lang/vim-elixir'

# window resize
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_start_key = '<C-W><C-R>'
'''

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
	let g:sonictemplate_vim_template_dir = ['~/.vim/template']
'''
